version: "3"
services:
  postgres:
    image: "postgres:13-alpine"
    restart: always
    environment:
      - POSTGRES_DB=surl
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=usr
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_DB=0
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  shorten_url:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=usr
      - DB_PASSWORD=usr
      - DB_NAME=surl
      - DB_SCHEMA=surl
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - API_VERSION=v1
    ports:
      - "8080:8080"
